-- ==========================================================
-- AUTOMATED 10-DAY NONOGRAM PUZZLES INSERT SCRIPT FOR SUPABASE
-- Includes 5x5, 10x10, and 15x15 varied pixel-art grids
-- ==========================================================

INSERT INTO public.daily_puzzles (date_string, category, title, width, height, solution, row_clues, col_clues)
VALUES
  (CURRENT_DATE, 'nonogram', 'לב ❤️', 5, 5, '[[false,true,false,true,false],[true,true,true,true,true],[true,true,true,true,true],[false,true,true,true,false],[false,false,true,false,false]]'::jsonb, '[[1,1],[5],[5],[3],[1]]'::jsonb, '[[2],[4],[4],[4],[2]]'::jsonb),
  (CURRENT_DATE + INTERVAL '1 day', 'nonogram', 'מגן דוד ✡️', 10, 10, '[[false,false,false,true,true,true,true,false,false,false],[false,false,true,false,false,false,false,true,false,false],[false,true,false,false,false,false,false,false,true,false],[true,true,true,true,true,true,true,true,true,true],[false,true,false,false,false,false,false,false,true,false],[false,true,false,false,false,false,false,false,true,false],[true,true,true,true,true,true,true,true,true,true],[false,true,false,false,false,false,false,false,true,false],[false,false,true,false,false,false,false,true,false,false],[false,false,false,true,true,true,true,false,false,false]]'::jsonb, '[[4],[1,1],[1,1],[10],[1,1],[1,1],[10],[1,1],[1,1],[4]]'::jsonb, '[[1,1],[1,4,1],[1,1,1,1],[3,3],[3,3],[3,3],[3,3],[1,1,1,1],[1,4,1],[1,1]]'::jsonb),
  (CURRENT_DATE + INTERVAL '2 days', 'nonogram', 'מנורת שבעת הקנים 🕎', 10, 10, '[[true,false,true,false,true,false,true,false,true,false],[true,false,true,false,true,false,true,false,true,false],[true,true,true,true,true,true,true,true,true,false],[true,false,false,false,true,false,false,false,true,false],[false,true,true,true,true,true,true,true,false,false],[false,false,false,false,true,false,false,false,false,false],[false,false,false,false,true,false,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,true,false,false,false,false],[false,false,true,true,true,true,true,false,false,false]]'::jsonb, '[[1,1,1,1,1],[1,1,1,1,1],[9],[1,1,1],[7],[1],[1],[3],[3],[5]]'::jsonb, '[[4],[1,1],[3,1,1],[1,1,3],[10],[1,1,3],[3,1,1],[1,1],[4],[0]]'::jsonb),
  (CURRENT_DATE + INTERVAL '3 days', 'nonogram', 'סירת מפרש ⛵', 10, 10, '[[false,false,false,false,true,false,false,false,false,false],[false,false,false,true,true,false,false,false,false,false],[false,false,true,true,true,false,false,false,false,false],[false,true,true,true,true,false,false,false,false,false],[true,true,true,true,true,false,false,false,false,false],[false,false,false,false,true,false,false,false,false,false],[true,true,true,true,true,true,true,true,true,true],[false,true,true,true,true,true,true,true,true,false],[false,false,true,true,true,true,true,true,false,false],[false,false,false,true,true,true,true,false,false,false]]'::jsonb, '[[1],[2],[3],[4],[5],[1],[10],[8],[6],[4]]'::jsonb, '[[1,1],[2,2],[3,3],[4,4],[10],[4],[4],[3],[2],[1]]'::jsonb),
  (CURRENT_DATE + INTERVAL '4 days', 'nonogram', 'תפוח 🍎', 10, 10, '[[false,false,false,false,true,true,false,false,false,false],[false,false,false,true,false,false,false,false,false,false],[false,true,true,false,false,true,true,true,false,false],[true,true,true,true,true,true,true,true,true,false],[true,true,true,true,true,true,true,true,true,false],[true,true,true,true,true,true,true,true,true,false],[true,true,true,true,true,true,true,true,true,false],[false,true,true,true,true,true,true,true,false,false],[false,false,true,true,true,true,true,false,false,false],[false,false,false,true,false,true,false,false,false,false]]'::jsonb, '[[2],[1],[2,3],[9],[9],[9],[9],[7],[5],[1,1]]'::jsonb, '[[4],[6],[7],[1,7],[1,6],[1,8],[7],[6],[4],[0]]'::jsonb),
  (CURRENT_DATE + INTERVAL '5 days', 'nonogram', 'בית 🏠', 10, 10, '[[false,false,false,false,true,true,false,false,false,false],[false,false,false,true,true,true,true,false,false,false],[false,false,true,true,true,true,true,true,false,false],[false,true,true,true,true,true,true,true,true,false],[true,true,true,true,true,true,true,true,true,true],[false,true,true,true,true,true,true,true,true,false],[false,true,true,false,false,true,true,true,true,false],[false,true,true,false,false,true,true,true,true,false],[false,true,true,true,true,true,true,true,true,false],[false,true,true,true,true,true,true,true,true,false]]'::jsonb, '[[2],[4],[6],[8],[10],[8],[2,4],[2,4],[8],[8]]'::jsonb, '[[1],[7],[8],[5,2],[6,2],[10],[9],[8],[7],[1]]'::jsonb),
  (CURRENT_DATE + INTERVAL '6 days', 'nonogram', 'עוגן ⚓', 10, 10, '[[false,false,false,false,true,true,false,false,false,false],[false,false,false,true,false,false,true,false,false,false],[false,false,false,false,true,true,false,false,false,false],[false,false,true,true,true,true,true,true,false,false],[false,false,false,false,true,true,false,false,false,false],[false,false,false,false,true,true,false,false,false,false],[true,false,false,false,true,true,false,false,false,true],[true,true,false,false,true,true,false,false,true,true],[false,true,true,true,true,true,true,true,true,false],[false,false,true,true,true,true,true,true,false,false]]'::jsonb, '[[2],[1,1],[2],[6],[2],[2],[1,2,1],[2,2,2],[8],[6]]'::jsonb, '[[2],[2],[1,2],[1,1,2],[1,8],[1,8],[1,1,2],[1,2],[2],[2]]'::jsonb),
  (CURRENT_DATE + INTERVAL '7 days', 'nonogram', 'חללית 🚀', 15, 15, '[[false,false,false,false,false,false,false,true,false,false,false,false,false,false,false],[false,false,false,false,false,false,true,true,true,false,false,false,false,false,false],[false,false,false,false,false,false,true,true,true,false,false,false,false,false,false],[false,false,false,false,false,true,true,true,true,true,false,false,false,false,false],[false,false,false,false,false,true,true,false,true,true,false,false,false,false,false],[false,false,false,false,false,true,true,true,true,true,false,false,false,false,false],[false,false,false,false,true,true,true,true,true,true,true,false,false,false,false],[false,false,false,false,true,true,true,true,true,true,true,false,false,false,false],[false,false,false,true,true,true,true,true,true,true,true,true,false,false,false],[false,false,true,true,true,true,true,true,true,true,true,true,true,false,false],[false,true,true,false,true,true,true,true,true,true,true,false,true,true,false],[true,true,false,false,true,true,true,true,true,true,true,false,false,true,true],[true,false,false,false,false,true,true,true,true,true,false,false,false,false,true],[false,false,false,false,false,false,true,true,true,false,false,false,false,false,false],[false,false,false,false,false,false,false,true,false,false,false,false,false,false]]'::jsonb, '[[1],[3],[3],[5],[2,2],[5],[7],[7],[9],[11],[2,7,2],[2,7,2],[1,5,1],[3],[1]]'::jsonb, '[[2],[2],[2],[2],[6],[10],[13],[4,10],[13],[10],[6],[2],[2],[2],[2]]'::jsonb),
  (CURRENT_DATE + INTERVAL '8 days', 'nonogram', 'כתר מלכות 👑', 15, 15, '[[true,false,false,false,false,false,true,true,true,false,false,false,false,false,true],[true,true,false,false,false,true,true,true,true,true,false,false,false,true,true],[true,true,true,false,true,true,true,true,true,true,true,false,true,true,true],[true,true,true,true,true,true,true,true,true,true,true,true,true,true,true],[true,true,true,true,true,true,true,true,true,true,true,true,true,true,true],[false,true,true,true,true,true,true,true,true,true,true,true,true,true,false],[false,false,true,true,true,true,true,true,true,true,true,true,true,false,false],[false,false,false,true,true,true,true,true,true,true,true,true,false,false,false],[false,false,false,true,true,true,true,true,true,true,true,true,false,false,false],[false,false,false,true,false,true,false,true,false,true,false,true,false,false,false],[false,false,true,true,true,true,true,true,true,true,true,true,true,false,false],[false,false,true,true,true,true,true,true,true,true,true,true,true,false,false],[true,true,true,true,true,true,true,true,true,true,true,true,true,true,true],[true,true,true,true,true,true,true,true,true,true,true,true,true,true,true],[true,true,true,true,true,true,true,true,true,true,true,true,true,true,true]]'::jsonb, '[[1,3,1],[2,5,2],[3,7,3],[15],[15],[13],[11],[9],[9],[1,1,1,1,1],[11],[11],[15],[15],[15]]'::jsonb, '[[5,3],[5,3],[5,5],[12],[7,5],[14],[9,5],[15],[9,5],[14],[7,5],[12],[5,5],[5,3],[5,3]]'::jsonb),
  (CURRENT_DATE + INTERVAL '9 days', 'nonogram', 'חתול 🐱', 10, 10, '[[true,true,false,false,false,false,false,false,true,true],[true,true,true,false,false,false,false,true,true,true],[true,true,true,true,true,true,true,true,true,true],[true,false,true,true,true,true,true,true,false,true],[true,true,true,true,true,true,true,true,true,true],[true,true,true,false,true,true,false,true,true,true],[false,true,true,true,true,true,true,true,true,false],[false,false,true,true,true,true,true,true,false,false],[false,false,true,true,false,false,true,true,false,false],[false,false,true,true,false,false,true,true,false,false]]'::jsonb, '[[2,2],[3,3],[10],[1,6,1],[10],[3,2,3],[8],[6],[2,2],[2,2]]'::jsonb, '[[6],[3,3],[9],[3,4],[6],[6],[3,4],[9],[3,3],[6]]'::jsonb)
ON CONFLICT (date_string) DO UPDATE SET
  title = EXCLUDED.title,
  width = EXCLUDED.width,
  height = EXCLUDED.height,
  solution = EXCLUDED.solution,
  row_clues = EXCLUDED.row_clues,
  col_clues = EXCLUDED.col_clues;
